version: '3.9'

services:
  app:
    container_name: security
    build:
      context: .
      dockerfile: Dockerfile
    image: app:latest
    ports:
      - "8889:8888"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/db-delivery-d
      - SPRING_DATASOURCE_USERNAME=user-db
      - SPRING_DATASOURCE_PASSWORD=cfkdghruhgurgh
      - SPRING_JPA_HIBERNATE_DDL_AUTO=none

  db:
    image: postgres:18
    restart: always
    container_name: postgres_db_container
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    volumes:
      - ./database:/docker-entrypoint-initdb.d.ro
      - data-security:/var/lib/postgresql/data
    ports:
      - ${POSTGRES_PORT}:5432

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - ${PG_PORT}:80
    depends_on:
      db:
        condition: service_healthy

volumes:
  data-security: