server:
  port: 8888
  

  
jwt:
  secret: ${JWT_SECRET}
  lifetime: ${JWT_LIFETIME}

spring:
  config:
    import: "optional:file:.env[.properties]"  
  jpa:
    show-sql: true
    database: postgresql
    # database-platform: org.hibernate.dialect.PostgreSQL10Dialect
    generate-ddl: false
    properties:
      hibernate:
        show_sql=true:
    hibernate:
      ddl-auto: none

  datasource:
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    url: jdbc:postgresql://localhost:${POSTGRES_PORT}/${POSTGRES_DB}
    driverClassName: org.postgresql.Driver


  flyway:
    url: ${spring.datasource.url}
    user: ${spring.datasource.username}
    password: ${spring.datasource.password}

  main:
    allow-circular-references: true