name: CI-Pipeline


on: 
  push:
    branches: 
      - main
  pull_request:
    branches: 
      - main
      - feature/*
    types: [opened, synchronize, reopened, closed] 

env:
  REGISTRY: ghcr.io   
  IMAGE_NAME: ${{ github.repository }}   

permissions:
  checks: write
  contents: read
  pull-requests: write


jobs:
  
  # changes:
  #   runs-on: ubuntu-latest
  #   outputs:
  #     src: |
  #       ${{ steps.filter.outputs.src }} 
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: dorny/paths-filter@v3
  #       id: filter
  #       with:
  #         filters: |
  #           src:
  #             - 'src/**'
  #             - 'sql/**' 
  #             - 'config/checkstyle/**' 
  #             - 'database/**' 
  #             - 'Dockerfile' 
  #             - 'docker-compose.*.yml' 
  #             - '*.gradle' 
  #             - 'gradlew' 
  #             - 'gradlew.*'

  lint:
    name: Run Checkstyle
    # needs: changes 
    # if: needs.changes.outputs.src == 'true'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ["25"]
    steps:
        
      - name: Checkout code
        uses: actions/checkout@v6
        # id: filter
        # with:
        #   filters: |
        #     src:
        #       - 'src/**'
        #     config:
        #       - 'config/checkstyle/**'  
        #     sql:
        #       - 'sql/**'  
        #     database:
        #       - 'database/**'  

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Gradle Checkstyle
        run: gradle checkstyleMain checkstyleTest

      - name: Publish Checkstyle Report
        uses: lcollins/checkstyle-github-action@v3.2.0
        with:
          path: '**/*.xml'
        if: always()

  test:
    needs: [lint]
    name: Run Tests
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        java-version: ["25"]
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
          cache: 'gradle'

      - name: Run Gradle Test
        run: gradle test

      - name: Upload HTML Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-reports-html
          path: |
            build/reports/tests/test/

      - name: Publish JUnit Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: Gradle Tests
          path: build/test-results/test/*.xml
          reporter: java-junit
  
  build:
    needs: [lint, test]
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        java-version: ["25"]

    permissions:
      contents: read
      packages: write 
      attestations: write
      id-token: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v6
        
      - name: Setup Homebrew for macOS
        if: runner.os == 'macOS'
        uses: Homebrew/actions/setup-homebrew@master

      - name: Setup Docker for macOS   
        if: runner.os == 'macOS'
        run: |
          brew install docker colima
          colima start
          # for work docker-compose v2
          mkdir -p ~/.docker/cli-plugins
          ln -sfn /usr/local/opt/docker-compose/bin/docker-compose ~/.docker/cli-plugins/docker-compose
      - name: Verify Docker
        run: |
          docker info

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@9ec57ed1fcdbf14dcef7dfbe97b2010124a938b7
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}.${{ github.sha }}
     
      - name: Build and push Docker image
        id: push
        uses: docker/build-push-action@f2a1d5e99d037542a71f64918e516c093c6f3fc4
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}   

      - name: Generate artifact attestation
        uses: actions/attest@v4
        with:
          subject-name: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME}}.${{ github.sha }}
          subject-digest: ${{ steps.push.outputs.digest }}
          push-to-registry: true          